#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
ASSETS_DIR="$ROOT_DIR/assets/about"
OUTPUT_FILE="$ROOT_DIR/src/app/fpaboutcontent.pas"

APP_INFO_FILE="$ASSETS_DIR/APP_INFO.txt"
AUTHOR_FILE="$ASSETS_DIR/AUTHOR.txt"
ACK_FILE="$ASSETS_DIR/ACKNOWLEDGMENTS.txt"
LICENSE_FILE="$ASSETS_DIR/THIRD_PARTY_LICENSES.txt"

log() {
  printf '==> %s\n' "$*"
}

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    printf 'Missing required about source file: %s\n' "$path" >&2
    exit 1
  fi
}

emit_pascal_string_literal() {
  local path="$1"
  local line
  local -a lines=()

  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    lines+=("$line")
  done <"$path"

  if [[ "${#lines[@]}" -eq 0 ]]; then
    printf "    '';\n"
    return 0
  fi

  local i
  local last_index=$(( ${#lines[@]} - 1 ))
  for i in "${!lines[@]}"; do
    line="${lines[$i]}"
    line="$(printf '%s' "$line" | sed "s/'/''/g")"
    if [[ "$i" -lt "$last_index" ]]; then
      printf "    '%s' + LineEnding +\n" "$line"
    else
      printf "    '%s';\n" "$line"
    fi
  done
}

generate_unit() {
  local tmp_file="$1"

  cat >"$tmp_file" <<'HEADER'
unit FPAboutContent;
{
  Auto-generated by scripts/generate_about_content.sh from assets/about/*.txt.
  Do not edit this file manually.
}

{$mode objfpc}{$H+}

interface

uses
  SysUtils;

type
  TAboutSection = (
    absAppInfo,
    absAuthor,
    absAcknowledgments,
    absThirdPartyLicenses
  );

function AboutSectionTitle(ASection: TAboutSection): string;
function AboutSectionText(ASection: TAboutSection): string;

const
  AboutAppInfoText =
HEADER

  emit_pascal_string_literal "$APP_INFO_FILE" >>"$tmp_file"
  cat >>"$tmp_file" <<'MIDDLE_1'

  AboutAuthorText =
MIDDLE_1
  emit_pascal_string_literal "$AUTHOR_FILE" >>"$tmp_file"
  cat >>"$tmp_file" <<'MIDDLE_2'

  AboutAcknowledgmentsText =
MIDDLE_2
  emit_pascal_string_literal "$ACK_FILE" >>"$tmp_file"
  cat >>"$tmp_file" <<'MIDDLE_3'

  AboutThirdPartyLicensesText =
MIDDLE_3
  emit_pascal_string_literal "$LICENSE_FILE" >>"$tmp_file"
  cat >>"$tmp_file" <<'FOOTER'

implementation

function AboutSectionTitle(ASection: TAboutSection): string;
begin
  case ASection of
    absAppInfo:
      Result := 'App Info';
    absAuthor:
      Result := 'Author';
    absAcknowledgments:
      Result := 'Acknowledgments';
    absThirdPartyLicenses:
      Result := 'Third-Party Licenses';
  else
    Result := 'About';
  end;
end;

function AboutSectionText(ASection: TAboutSection): string;
begin
  case ASection of
    absAppInfo:
      Result := AboutAppInfoText;
    absAuthor:
      Result := AboutAuthorText;
    absAcknowledgments:
      Result := AboutAcknowledgmentsText;
    absThirdPartyLicenses:
      Result := AboutThirdPartyLicensesText;
  else
    Result := AboutAppInfoText;
  end;
end;

end.
FOOTER
}

main() {
  require_file "$APP_INFO_FILE"
  require_file "$AUTHOR_FILE"
  require_file "$ACK_FILE"
  require_file "$LICENSE_FILE"

  local tmp_file
  tmp_file="$(mktemp "${TMPDIR:-/tmp}/fpaboutcontent.XXXXXX")"
  trap '[[ -n "${tmp_file:-}" ]] && rm -f "$tmp_file"' EXIT

  generate_unit "$tmp_file"

  if [[ -f "$OUTPUT_FILE" ]] && cmp -s "$tmp_file" "$OUTPUT_FILE"; then
    log "About content unit is already up to date"
    return 0
  fi

  cp "$tmp_file" "$OUTPUT_FILE"
  log "Regenerated $OUTPUT_FILE from assets/about/*.txt"
}

main "$@"
